export const GET_START = 'GISTS_GET_START';
export const GET_SUCCESS = 'GISTS_GET_SUCCESS';
export const GET_FAILURE = 'GISTS_GET_FAILURE';
export const GET_STARRED_SUCCESS = 'GISTS_GET_STARRED_SUCCESS';
export const CHANGE_FILTER = 'CHANGE_FILTER';

export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCED = 'GET_USER_SUCCED';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD';


